import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Types } from 'mongoose';

export type CommunicationType =
  | 'ANNOUNCEMENT' | 'CIRCULAR' | 'BULLETIN' | 'CAMPAIGN'
  | 'EMERGENCY_NOTICE' | 'POLICY_COMMUNICATION'
  | 'PROCEDURE_COMMUNICATION' | 'TRAINING_COMMUNICATION';

export type CommunicationPriority = 'INFORMATIVE' | 'IMPORTANT' | 'URGENT' | 'CRITICAL';

export type TargetAudienceType =
  | 'ALL_COMPANY' | 'AREA' | 'POSITION' | 'INDIVIDUAL'
  | 'COPASST' | 'COMMITTEE' | 'BRIGADE' | 'MANAGERS' | 'SST_TEAM';

export type CommunicationStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';

@Schema({ timestamps: true })
export class Communication {
  _id!: Types.ObjectId;

  @Prop({ required: true })
  companyId!: string;

  @Prop({ required: true })
  title!: string;

  @Prop()
  body?: string;

  @Prop({ required: true, enum: ['ANNOUNCEMENT','CIRCULAR','BULLETIN','CAMPAIGN','EMERGENCY_NOTICE','POLICY_COMMUNICATION','PROCEDURE_COMMUNICATION','TRAINING_COMMUNICATION'] })
  communicationType!: CommunicationType;

  @Prop({ required: true, enum: ['INFORMATIVE','IMPORTANT','URGENT','CRITICAL'], default: 'INFORMATIVE' })
  priority!: CommunicationPriority;

  @Prop({ required: true, enum: ['ALL_COMPANY','AREA','POSITION','INDIVIDUAL','COPASST','COMMITTEE','BRIGADE','MANAGERS','SST_TEAM'] })
  targetAudience!: TargetAudienceType;

  @Prop({ type: [String] })
  targetIds: string[] = [];

  @Prop({ required: true, enum: ['DRAFT','PUBLISHED','ARCHIVED'], default: 'DRAFT' })
  status!: CommunicationStatus;

  @Prop()
  publishedAt?: string;

  @Prop()
  scheduledAt?: string;

  @Prop()
  expiresAt?: string;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  createdBy?: Types.ObjectId;

  @Prop()
  createdByName?: string;

  @Prop({ type: [String] })
  linkedDocumentIds: string[] = [];

  @Prop()
  attachmentUrls?: string[];

  @Prop({ default: false })
  requiresSignature!: boolean;

  @Prop({ default: false })
  requiresSurvey!: boolean;

  @Prop({ type: Types.ObjectId, ref: 'CommunicationSurvey' })
  surveyId?: Types.ObjectId;

  @Prop({ default: false })
  isFromAutoGeneration!: boolean;

  @Prop()
  autoGeneratedFromModule?: string;

  @Prop()
  autoGeneratedFromEntityId?: string;
}

export const CommunicationSchema = SchemaFactory.createForClass(Communication);
