import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { Communication } from './schemas/communication.schema';
import { CommunicationRecipient } from './schemas/communication-recipient.schema';
import { CommunicationHistory } from './schemas/communication-history.schema';
import { AlertsService } from '../alerts/alerts.service';
import { AlertSeverity } from '../alerts/schemas/alert.schema';
import { Employee } from '../employees/schemas/employee.schema';

export type AutoCommunicationModule =
  | 'POLICY_CREATED'
  | 'POLICY_UPDATED'
  | 'TRAINING_ASSIGNED'
  | 'COPASST_ELECTION'
  | 'COMMITTEE_ELECTION'
  | 'EMERGENCY_DRILL'
  | 'EMERGENCY_PLAN_UPDATED'
  | 'PROCEDURE_UPDATED'
  | 'AUDIT_RESULTS'
  | 'CONVIVENCIA_ELECTION'
  | 'CONVIVENCIA_CAMPAIGN'
  | 'CONVIVENCIA_VOTING'
  | 'DOCUMENT_PUBLISHED';

export interface AutoCommunicationPayload {
  companyId: Types.ObjectId | string;
  title: string;
  body: string;
  communicationType: 'POLICY_COMMUNICATION' | 'PROCEDURE_COMMUNICATION' | 'TRAINING_COMMUNICATION' | 'EMERGENCY_NOTICE' | 'ANNOUNCEMENT';
  priority?: 'INFORMATIVE' | 'IMPORTANT' | 'URGENT' | 'CRITICAL';
  targetAudience?: 'ALL_COMPANY' | 'COPASST' | 'COMMITTEE' | 'MANAGERS' | 'SST_TEAM' | 'BRIGADE';
  requiresSignature?: boolean;
  sourceModule: AutoCommunicationModule;
  sourceEntityId?: string;
  linkedDocumentIds?: string[];
  attachmentUrls?: string[];
}

@Injectable()
export class AutoCommunicationService {
  constructor(
    @InjectModel(Communication.name) private commModel: Model<Communication>,
    @InjectModel(CommunicationRecipient.name) private recipientModel: Model<CommunicationRecipient>,
    @InjectModel(CommunicationHistory.name) private historyModel: Model<CommunicationHistory>,
    @InjectModel(Employee.name) private employeeModel: Model<Employee>,
    private alertsService: AlertsService,
  ) {}

  /**
   * Auto-generates a communication, publishes it, assigns recipients,
   * and records audit history. Returns the created Communication.
   */
  async generateCommunication(payload: AutoCommunicationPayload): Promise<Communication> {
    const companyOid = typeof payload.companyId === 'string'
      ? new Types.ObjectId(payload.companyId)
      : payload.companyId;

    // 1. Create the communication as DRAFT initially
    const comm = await this.commModel.create({
      companyId: companyOid,
      title: payload.title,
      body: payload.body,
      communicationType: payload.communicationType,
      priority: payload.priority || 'IMPORTANT',
      targetAudience: payload.targetAudience || 'ALL_COMPANY',
      targetIds: [],
      status: 'DRAFT',
      requiresSignature: payload.requiresSignature ?? false,
      isFromAutoGeneration: true,
      autoGeneratedFromModule: payload.sourceModule,
      autoGeneratedFromEntityId: payload.sourceEntityId,
      linkedDocumentIds: payload.linkedDocumentIds || [],
      attachmentUrls: payload.attachmentUrls || [],
      createdByName: 'Sistema Automático',
    });

    // 2. Auto-publish
    comm.status = 'PUBLISHED';
    comm.publishedAt = new Date().toISOString();
    await comm.save();

    // 3. Assign recipients based on target audience
    const recipientEmployees = await this.resolveRecipients(companyOid, payload.targetAudience || 'ALL_COMPANY');

    if (recipientEmployees.length > 0) {
      const recipientDocs = recipientEmployees.map((emp) => ({
        companyId: companyOid,
        communicationId: comm._id,
        employeeId: (emp as unknown as { _id: Types.ObjectId })._id,
        employeeName: emp.name,
        employeeEmail: '',
        status: 'PENDING' as const,
        deliveredAt: new Date().toISOString(),
      }));
      await this.recipientModel.insertMany(recipientDocs);
    }

    // 4. Record history
    await this.historyModel.create({
      companyId: companyOid,
      userId: new Types.ObjectId(), // system user
      userEmail: 'system@auto-generation',
      userName: 'Sistema Automático',
      action: 'AUTO_GENERATE',
      entityType: 'Communication',
      entityId: comm._id.toString(),
      description: `Comunicación auto-generada: ${payload.title} (${payload.sourceModule})`,
      newValue: { sourceModule: payload.sourceModule, title: payload.title, type: payload.communicationType },
    });

    // 5. Create alert
    await this.alertsService.create({
      companyId: companyOid.toString(),
      type: 'AUTO_COMMUNICATION',
      message: `Nueva comunicación automática: ${payload.title}`,
      severity: payload.communicationType === 'EMERGENCY_NOTICE' ? AlertSeverity.HIGH : AlertSeverity.MEDIUM,
    });

    return comm;
  }

  /**
   * Resolve employee recipients based on target audience type.
   */
  private async resolveRecipients(
    companyId: Types.ObjectId,
    audience: 'ALL_COMPANY' | 'COPASST' | 'COMMITTEE' | 'MANAGERS' | 'SST_TEAM' | 'BRIGADE',
  ): Promise<Employee[]> {
    const baseFilter: Record<string, unknown> = { companyId, status: 'Activo' };

    switch (audience) {
      case 'ALL_COMPANY':
        return this.employeeModel.find(baseFilter).exec();
      case 'MANAGERS':
        return this.employeeModel.find({ ...baseFilter, position: /gerente|manager|director/i }).exec();
      case 'SST_TEAM':
        return this.employeeModel.find({ ...baseFilter, area: /sst|seguridad|salud/i }).exec();
      case 'COPASST':
      case 'COMMITTEE':
      case 'BRIGADE':
        // For these specific groups, we send to all employees as the system
        // broadcasts the election/event to the whole company
        return this.employeeModel.find(baseFilter).exec();
      default:
        return this.employeeModel.find(baseFilter).exec();
    }
  }
}
